MVCTutorial/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTutorial.Models;
using MVCTutorial.Dal;
using MVCTutorial.ViewModel;
using System.Web.Security;
using System.Threading;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

namespace MVCTutorial.Controllers
{
    public class BranchController : Controller
    {
        // GET: Branch
        public ActionResult Index()
        {
            return View();
        }

        public ViewResult ShowMap()
        {
            Session["PageTitle"] = "Our Branches";
            return View();
        }

        public JsonResult getLocations()
        {
            DataLayer Pdal = new DataLayer();
            List<Location> objLocations = Pdal.Locations.ToList<Location>();

            JavaScriptSerializer x = new JavaScriptSerializer();
            string JSONString = x.Serialize(objLocations);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }
    }
}

MVCTutorial/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTutorial.Models;
using MVCTutorial.Dal;
using MVCTutorial.ViewModel;
using System.Web.Security;
using System.Threading;
using System.Data.Entity.Validation;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;

namespace MVCTutorial.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ViewResult Index()
        {
            return View();
        }

        // web service!!
        public async Task<JsonResult> GetCurrentDollarJson(string currCoin)
        {
            try {
                HttpClient client = new HttpClient();
                var responseString = await client.GetStringAsync("https://api.exchangeratesapi.io/latest?symbols=" + currCoin);
                return Json(responseString, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(1, JsonRequestBehavior.AllowGet);
            }
            
        }

        public ActionResult ShowOrders()//return view of show orders page
        {
            if (HttpContext.Request.Cookies["Manager"] != null)
            {
                Session["PageTitle"] = "Orders";
                return View();
            }
            else
            {
                return RedirectToAction("ShowSignInPage", "Auth");
            }
        }
        private IEnumerable<OrderProductViewModel> GetOrderedProducts()
        {
            DataLayer Pdal = new DataLayer();
            List<Order> objOrders = Pdal.Orders.ToList<Order>();
            List<Product> objProducts = Pdal.Products.ToList<Product>();
            var orderProductViewModel = from product in objProducts
                                        join order in objOrders
                                        on product.productID equals order.productID
                                        into result
                                        from newOrder in result.DefaultIfEmpty()
                                        select new OrderProductViewModel { product = product, order = newOrder };
            return orderProductViewModel;
        }
        public JsonResult GetOrderByJson()//return json with all the current orders
        {
            var orderedProducts = GetOrderedProducts();
            return Json(orderedProducts, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ShowReservationPage()
        {
            if (HttpContext.Request.Cookies["Supplier"] != null)
            {
                String data = HttpContext.Request.Cookies.Get("Supplier").Value;
                User user = new User();
                user.userID = (String)JObject.Parse(data)["userID"];
                user.name = (String)JObject.Parse(data)["name"];
                user.permission = (int)JObject.Parse(data)["permission"];
                user.password = (String)JObject.Parse(data)["password"];
                Session["PageTitle"] = "New Order";
                Session["LogginInUser"] = user.name;
                return View(user);
            }
            else
            {
                return RedirectToAction("ShowSignInPage", "Auth");
            }


        }
        public JsonResult MakeOrder()
        {
            Order o = new Order();
            DataLayer Pdal = new DataLayer();
            o.productID = Request.Form["txtProductID"];//Taking information from the form
            o.supplierID = Request.Form["txtUserID"];
            o.amount = Int32.Parse(Request.Form["txtOption"]);
            o.orderDate = DateTime.Now.ToString("dd-MM-yyyy hh:mm:ss tt"); ;

            ViewBag.Error = TempData[""];

            //DataLayer Pdal = new DataLayer();
            List<Product> objProducts =
             (from x in Pdal.Products
              where (x.productID.Equals(o.productID))//Finding the desired product in data base
              select x).ToList<Product>();

            if ((objProducts[0].initialAmount >= o.amount))//If there is enough in stock you can to buy
            {
                List<Order> objO = Pdal.Orders.ToList<Order>();
                //find the max orderID
                var maxOrderID = -1;
                foreach (Order order in objO)
                {
                    if (Int32.Parse(order.orderID) > maxOrderID)
                    {
                        maxOrderID = Int32.Parse(order.orderID);
                    }
                }
                o.orderID = (maxOrderID + 1).ToString();
                //o.productName = objProducts[0].productName;
                objProducts[0].initialAmount -= o.amount;
                Pdal.Orders.Add(o);//add order to data base

                try
                {
                    Pdal.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    ViewBag.Error = TempData["there was problem. please try again"];
                }
            }
            else ViewBag.Error = TempData["not enough in stock"];
            List<Order> objOrders = Pdal.Orders.ToList<Order>();
            objProducts = Pdal.Products.ToList<Product>();
            return Json(objProducts, JsonRequestBehavior.AllowGet);//return json with all the current products 
        }

        [HttpDelete]
        public JsonResult DeleteOrderByJson(string id)
        {
            DataLayer Pdal = new DataLayer();
            List<Order> objOrders =
               (from x in Pdal.Orders
                where (x.orderID.Equals(id.ToString()))
                select x).ToList<Order>();
            if (objOrders.Count == 1)
            {
                Pdal.Orders.Remove(objOrders[0]);
                Pdal.SaveChanges();//update data base
            }
            return GetOrderByJson();
        }

        [HttpPut]
        public JsonResult ChangeOrderAmount(string id, string orderAmount, string newAmount)
        {
            DataLayer Pdal = new DataLayer();
            List<Order> objOrders =
               (from x in Pdal.Orders
                where (x.orderID.Equals(id.ToString()))
                select x).ToList<Order>();
            if (objOrders == null) return null;
            var productID = objOrders.First().productID;
            //change the product amount left
            List<Product> productToEdit =
             (from x in Pdal.Products
              where (x.productID.Equals(productID))//Finding the desired product in data base
              select x).ToList<Product>();
            // current amount = DB amount + amount that were ordered(return the bought) - the new amount bought;
            productToEdit.First().initialAmount = productToEdit.First().initialAmount + Int32.Parse(orderAmount) - Int32.Parse(newAmount);
            //update the order amount
            objOrders.First().amount = Int32.Parse(newAmount);
            Pdal.SaveChanges();//update data base

            return GetOrderByJson();
        }
        [HttpPost]
        public JsonResult SearchOrder(string productID, string productName, string supplierID)
        {
            var orderedProducts = GetOrderedProducts();
            List<OrderProductViewModel> results = null;

            foreach (var orderProduct in orderedProducts)
            {
                results =
                  (from x in orderedProducts
                   where (x.order != null) && ((productID != "All" ? x.product.productID.Equals(productID) : true) && (productName != "All" ? x.product.productType.Equals(productName) : true)
                   && (supplierID != "" ? (x.order != null && x.order.supplierID.Equals(supplierID)) : true))
                   select x).ToList();
            }

            return Json(results, JsonRequestBehavior.AllowGet);
        }
    }


}

MVCTutorial/Views/Shared/MDB.cshtml
 <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
<link href="css/addons/flag.min.css" rel="stylesheet">

MVCTutorial/Views/Shared/ManagerNavbar.cshtml
﻿<nav class="mb-3 navbar navbar-expand-lg navbar-dark default-color">
    <span class="navbar-brand">
        <img width="26" src="~/Content/img/2102407.png" />
        <span class="title" style="margin-left:3px; margin-top:2px">@Session["PageTitle"]</span>
    </span>

    <div class="collapse navbar-collapse first-nav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowManagerPage", "Manager")">
                    <i class="fas fa-home fa-lg"></i> DashBoard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowStock","Product")">
                    <i class="fas fa-layer-group fa-lg"></i> Stock
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowOrders","Order")">
                    <i class="fas fa-file-invoice-dollar fa-lg"></i>  Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowSuppliers","Supplier")">
                    <i class="fas fa-address-book fa-lg"></i>  Suppliers
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item facebook-icon">
                <nav>
                    <a class="waves-effect waves-light" href="https://www.facebook.com/Clothes-Stock-101478944606926">
                        <i class="fab fa-facebook fa-lg"></i>
                    </a>
                </nav>
            </li>

            <li class="nav-item span">
                <div>
                    Welcome Back @Session["LogginInUser"]!
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link user-nav">
                    <i class="fas fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="@Url.Action("ShowProfilePage","Profile")">
                        <i class="fas fa-id-card fa-lg"></i><span class="label">Profile</span>
                    </a>
                    <a class="dropdown-item" href="@Url.Action("ShowSignInPage","Auth")">
                        <i class="fas fa-sign-out-alt"></i><span class="label">Log Out</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>

MVCTutorial/Views/Shared/Navbar.cshtml
﻿<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
        <span class="navbar-brand">
            <img width="26" src="~/Content/img/2102407.png" />
            <span class="title" style="margin-left:3px; margin-top:2px">@Session["PageTitle"]</span>
        </span>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" id="home-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowHomePage","Home")">
                        Home
                    </a>
                </li>
                <li class="nav-item" id="signin-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowSignInPage","Auth")">Sign In</a>
                </li>
                <li class="nav-item" id="signup-nav-item">
                    <a class="nav-link" href="@Url.Action("ShowSignUpPage","Auth")">Sign Up</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

MVCTutorial/Views/Shared/SupplierNavbar.cshtml
﻿<nav class="mb-3 navbar navbar-expand-lg navbar-dark default-color">
    <span class="navbar-brand">
        <img width="26" src="~/Content/img/2102407.png" />
        <span class="title" style="margin-left:3px; margin-top:2px">@Session["PageTitle"]</span>
    </span>

    <div class="collapse navbar-collapse first-nav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowSupplierPage","Supplier")">
                    <i class="fas fa-home fa-lg"></i> DashBoard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowReservationPage","Order")">
                    <i class="fas fa-clipboard-list fa-lg"></i>  New Order
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowMyReservations","Supplier")">
                    <i class="fas fa-shopping-cart fa-lg"></i>  My Cart
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ShowMap","Branch")">
                    <i class="fas fa-map-marker-alt fa-lg"></i>  Branches
                </a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item facebook-icon">
                <nav>
                    <a class="waves-effect waves-light" href="https://www.facebook.com/Clothes-Stock-101478944606926">
                        <i class="fab fa-facebook fa-lg"></i>
                    </a>
                </nav>

            </li>
            <li class="nav-item span">
                <div>
                    Welcome Back @Session["LogginInUser"]!
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link user-nav">
                    <i class="fas fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="@Url.Action("ShowProfilePage","Profile")">
                        <i class="fas fa-id-card fa-lg"></i><span class="label">Profile</span>
                    </a>
                    <a class="dropdown-item" href="@Url.Action("ShowSignInPage","Auth")">
                        <i class="fas fa-sign-out-alt"></i><span class="label">Log Out</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>

MVCTutorial/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Html.Partial("MDB")
    @Styles.Render("~/Content/css/bootstrap")
    @Styles.Render("~/Content/css/Common")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="view">
        <div class="mask rgba-gradient align-items-center">
            <div class="container">
                <!--Grid row-->
                <div class="mask rgba-gradient align-items-center">
                    <div class="container">
                        
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</body>
</html>